sudo: false
dist: trusty
language: php
cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - node_modules
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
install:
  - yarn install
  - composer self-update
  - composer install --prefer-dist
  - locale -a
before_script:
  - PATH=${PATH//:\.\/node_modules\/\.bin/}
script:
  - make eslint
  - make clean
  - make check_permissions
  - make all_tests
